# The native module, `src/lib.rs`. It is the package's internals, not its API:
# the modules beside this one wrap it in the API a user sees.

from collections.abc import Iterable
from pathlib import Path
from typing import Any, Final, final

FORMAT_VERSION: Final[int]

def engine_version() -> str: ...

@final
class Layout:
    def __init__(self, cls: type, fields: list[tuple[str, str, Any]]) -> None: ...

@final
class NativeSchema:
    def __init__(
        self,
        version: int,
        collections: list[tuple[str, list[tuple[str, Any, str, Any, bool, bool]]]],
    ) -> None: ...

@final
class Param:
    index: int
    def __init__(self, index: int) -> None: ...

@final
class NativeQuery: ...

def compile_query(
    collection: str,
    filter: tuple[Any, ...] | None,
    sort: list[tuple[list[str], bool]],
    offset: int,
    limit: int | None,
) -> NativeQuery: ...
def parse_query(text: str) -> NativeQuery: ...

_Secret = bytes | bytearray | memoryview | str

@final
class NativeTransaction:
    @property
    def is_open(self) -> bool: ...
    def get(self, collection: str, layout: Layout, key: Any) -> Any: ...
    def find(
        self, collection: str, layout: Layout, query: NativeQuery, parameters: tuple[object, ...]
    ) -> list[Any]: ...
    def find_one(
        self, collection: str, layout: Layout, query: NativeQuery, parameters: tuple[object, ...]
    ) -> Any: ...
    def count(self, collection: str, query: NativeQuery, parameters: tuple[object, ...]) -> int: ...
    def insert(self, collection: str, layout: Layout, obj: object) -> Any: ...
    def insert_many(
        self, collection: str, layout: Layout, objects: Iterable[object]
    ) -> list[Any]: ...
    def put(self, collection: str, layout: Layout, obj: object) -> Any: ...
    def put_many(self, collection: str, layout: Layout, objects: Iterable[object]) -> list[Any]: ...
    def update(
        self, collection: str, layout: Layout, key: Any, changes: dict[str, object]
    ) -> bool: ...
    def delete(self, collection: str, key: Any) -> bool: ...
    def commit(self, deferred: bool) -> None: ...
    def end(self) -> None: ...
    @property
    def previous_version(self) -> int: ...
    @property
    def version(self) -> int: ...
    def next_step(self) -> int | None: ...
    def previous_keys(self, collection: str) -> list[Any]: ...
    def previous(self, collection: str, key: Any) -> dict[str, Any] | None: ...
    def finish(self) -> NativeDatabase: ...

@final
class NativeDatabase:
    @property
    def is_open(self) -> bool: ...
    @property
    def page_size(self) -> int: ...
    @property
    def format_version(self) -> int: ...
    @property
    def is_encrypted(self) -> bool: ...
    def begin_read(self) -> NativeTransaction: ...
    def begin_write(self) -> NativeTransaction: ...
    def sync(self) -> None: ...
    def check(self) -> dict[str, Any]: ...
    def upgrade_format(self) -> bool: ...
    def compact(self) -> dict[str, Any]: ...
    def backup(
        self,
        path: str | Path,
        key: _Secret | None = None,
        password: _Secret | None = None,
        password_hashing: tuple[int, int, int] | None = None,
    ) -> dict[str, Any]: ...
    def set_key(self, key: _Secret) -> None: ...
    def set_password(self, password: _Secret) -> None: ...
    def close(self) -> None: ...

def open(
    path: str | Path,
    *,
    create: bool | None = None,
    page_size: int | None = None,
    busy_timeout: float | None = None,
    cache_size: int | None = None,
    schema: NativeSchema | None = None,
    migrations: list[Any] = ...,
    key: _Secret | None = None,
    password: _Secret | None = None,
    password_hashing: tuple[int, int, int] | None = None,
    upgrade_format: bool | None = None,
) -> NativeDatabase | NativeTransaction: ...
def salvage(
    source: str | Path,
    target: str | Path,
    *,
    key: _Secret | None = None,
    password: _Secret | None = None,
    busy_timeout: float | None = None,
) -> dict[str, Any]: ...
