builders:
  darudb:
    import: "package:darudb_generator/builder.dart"
    builder_factories: ["darudbBuilder"]
    build_extensions: {".dart": [".darudb.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
